# Generated by Django 6.0.5 on 2026-06-22 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_coupon_expiredcoupon_validcoupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(default=0)),
                ('category_above', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='above_links', to='products.category')),
                ('category_below', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='below_links', to='products.category')),
            ],
            options={
                'unique_together': {('category_above', 'category_below')},
            },
        ),
    ]
