# Generated by Django 6.0.5 on 2026-06-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_categorytree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('available', 'Available'), ('discontinued', 'Discontinued')], default='draft', max_length=20),
        ),
    ]
