# Generated by Django 6.0.5 on 2026-07-06 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_warehouse_warehousemovement_warehousestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousestock',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Threshold for low stock alert', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
