# Generated by Django 6.0.5 on 2026-07-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_warehousestock_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='city',
            field=models.CharField(blank=True, help_text='City this warehouse serves for shipping', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warehousemovement',
            name='dest_after',
            field=models.PositiveIntegerField(blank=True, help_text='Destination warehouse stock AFTER this move', null=True),
        ),
        migrations.AddField(
            model_name='warehousemovement',
            name='source_after',
            field=models.PositiveIntegerField(blank=True, help_text='Source warehouse stock AFTER this move', null=True),
        ),
        migrations.AlterField(
            model_name='warehousemovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Adjustment')], help_text='Why did this movement happen', max_length=20),
        ),
    ]
