# Generated by Django 6.0.5 on 2026-07-09 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_user'),
        ('products', '0009_warehouse_city_warehousemovement_dest_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse that stock was deducted from for this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_order_items', to='products.warehouse'),
        ),
    ]
