# Generated by Django 6.0.5 on 2026-07-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, help_text='City for shipping eligibility check', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='managed_warehouses',
            field=models.JSONField(blank=True, default=list, help_text='Warehouse IDs this manager can access. Example: [1, 5, 10]'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller'), ('admin', 'Admin'), ('warehouse_manager', 'Warehouse Manager')], default='customer', max_length=20),
        ),
    ]
