# Generated by Django 6.0.5 on 2026-07-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_city_customuser_managed_warehouses_and_more'),
        ('products', '0009_warehouse_city_warehousemovement_dest_after_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='managed_warehouses',
        ),
        migrations.AddField(
            model_name='customuser',
            name='managed_warehouses',
            field=models.ManyToManyField(blank=True, help_text='Warehouses this manager can access', related_name='managers', to='products.warehouse'),
        ),
    ]
