# Generated by Django 6.0.5 on 2026-07-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_customuser_managed_warehouses_and_more'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='managed_warehouses',
            field=models.ManyToManyField(blank=True, help_text='Warehouses this manager can access', related_name='managers', to='warehouses.warehouse'),
        ),
    ]
