# Generated by Django 6.0.5 on 2026-06-15 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('back_in_stock', 'Back In Stock')], help_text='Why was this alert created?', max_length=20)),
                ('stock_at_trigger', models.PositiveIntegerField(help_text='Stock quantity when alert was created')),
                ('threshold', models.PositiveIntegerField(default=10, help_text='Alert when stock goes below this number')),
                ('is_resolved', models.BooleanField(default=False, help_text='Has someone addressed this alert?')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When was this alert resolved?', null=True)),
                ('resolution_note', models.TextField(blank=True, help_text='Notes about how this was resolved', null=True)),
                ('email_sent', models.BooleanField(default=False, help_text='Was an email notification sent?')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Product that triggered this alert', on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='products.product')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Who resolved this alert?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Alert',
                'verbose_name_plural': 'Stock Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='inventory_s_product_5b8c97_idx'), models.Index(fields=['alert_type', 'is_resolved'], name='inventory_s_alert_t_692cc6_idx'), models.Index(fields=['is_resolved', '-created_at'], name='inventory_s_is_reso_bca05b_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Adjustment'), ('return', 'Return')], help_text='Why did stock change?', max_length=20)),
                ('quantity', models.PositiveIntegerField(help_text='Number of units that moved')),
                ('previous_stock', models.PositiveIntegerField(help_text='Stock level BEFORE this movement')),
                ('new_stock', models.PositiveIntegerField(help_text='Stock level AFTER this movement')),
                ('reason', models.CharField(help_text='Human-readable reason: "Order #123", "Monthly count", "Damaged"', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who initiated this movement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='The order that caused this movement (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.order')),
                ('product', models.ForeignKey(help_text='The product whose stock changed', on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='inventory_s_product_cfb4fb_idx'), models.Index(fields=['movement_type', '-created_at'], name='inventory_s_movemen_a71f62_idx'), models.Index(fields=['created_by', '-created_at'], name='inventory_s_created_db949a_idx'), models.Index(fields=['created_at'], name='inventory_s_created_05ebf5_idx')],
            },
        ),
    ]
